name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: hai
        run: java -version
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: :shadowJar
      - name: Upload plugin jar artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: plugin jar
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/ajHologramConnector*.jar
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
      - name: Upload build files artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: build-files
          # A file, directory or wildcard pattern that describes what to upload
          path: '*/build/*'
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
          retention-days: 2
  deploy:
    runs-on: ubuntu-latest
    environment: maven-repo-deploy
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-files
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: hai
        run: java -version
      - name: Deploy with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: :publish
